import {test} from 'node:test';
import assert from 'node:assert/strict';
import {blankDraft,parseDraft,validateDraft,sections,projectFields,readableBrief} from './intake.ts';
function complete(){const draft=blankDraft();const fill=fields=>Object.fromEntries(fields.filter(f=>f.required).map(f=>[f.key,f.type==='email'?'designer@example.com':f.type==='url'?'https://example.com/photos':f.options?.[0]??'Sample content']));draft.values=fill(sections.flatMap(s=>s.fields));draft.projects[0].values=fill(projectFields);draft.consent=true;return draft}
test('a complete brief survives export/import without losing project order or answers',()=>{const d=complete();d.projects.push({id:'second',values:{...d.projects[0].values,title:'Second'}});assert.deepEqual(parseDraft(JSON.parse(JSON.stringify(d))),d);assert.equal(validateDraft(d).length,0)});
test('missing fields and consent prevent final export',()=>{assert.ok(validateDraft(blankDraft()).length>10);const d=complete();d.consent=false;assert.ok(validateDraft(d).some(e=>e.includes('зөвшөөрөл')))});
test('rejects unsafe links, invalid emails and unsupported selections',()=>{const d=complete();d.values.portrait='javascript:alert(1)';d.values.publicEmail='bad';d.projects[0].values.category='invalid';assert.equal(validateDraft(d).length,3)});
test('imports reject malformed, oversized, duplicate and empty project records',()=>{const d=complete();assert.equal(parseDraft(null),null);assert.equal(parseDraft({...d,version:2}),null);assert.equal(parseDraft({...d,projects:[]}),null);assert.equal(parseDraft({...d,projects:[d.projects[0],d.projects[0]]}),null);assert.equal(parseDraft({...d,values:{bio:42}}),null);assert.equal(parseDraft({...d,values:{bio:'a'.repeat(10001)}}),null)});
test('readable export includes optional notes, permissions and credit',()=>{const d=complete();d.projects[0].values.restrictions='Do not publish the client name';const output=readableBrief(d);assert.match(output,/Do not publish the client name/);assert.match(output,/Мэдээлэл боловсруулах зөвшөөрөл: Тийм/)});
